# Generated by Django 3.2.6 on 2021-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('dt', models.CharField(max_length=32)),
                ('min_temp', models.CharField(max_length=32)),
                ('max_temp', models.CharField(max_length=32)),
                ('weather', models.CharField(max_length=32)),
                ('wind', models.CharField(max_length=32)),
            ],
        ),
    ]
